package core

func MakeConfig() map[string]any {
	return map[string]any{
		"main": map[string]any{
			"name": "DutchCustomerData",
		},
		"feature": map[string]any{
			"test": map[string]any{
				"options": map[string]any{
					"active": false,
				},
			},
		},
		"options": map[string]any{
			"base": "https://free.bedrijfsdata.nl/v1.1",
			"headers": map[string]any{
				"content-type": "application/json",
			},
			"entity": map[string]any{
				"eu_ap_i": map[string]any{},
				"global_ap_i": map[string]any{},
				"netherlands_ap_i": map[string]any{},
			},
		},
		"entity": map[string]any{
			"eu_ap_i": map[string]any{
				"fields": []any{
					map[string]any{
						"active": true,
						"name": "active",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 0,
					},
					map[string]any{
						"active": true,
						"name": "address",
						"req": false,
						"type": "`$STRING`",
						"index$": 1,
					},
					map[string]any{
						"active": true,
						"name": "buyer",
						"req": false,
						"type": "`$STRING`",
						"index$": 2,
					},
					map[string]any{
						"active": true,
						"name": "buyer_country",
						"req": false,
						"type": "`$STRING`",
						"index$": 3,
					},
					map[string]any{
						"active": true,
						"name": "city",
						"req": false,
						"type": "`$STRING`",
						"index$": 4,
					},
					map[string]any{
						"active": true,
						"name": "contract_nature",
						"req": false,
						"type": "`$STRING`",
						"index$": 5,
					},
					map[string]any{
						"active": true,
						"name": "country",
						"req": false,
						"type": "`$STRING`",
						"index$": 6,
					},
					map[string]any{
						"active": true,
						"name": "html",
						"req": false,
						"type": "`$STRING`",
						"index$": 7,
					},
					map[string]any{
						"active": true,
						"name": "id",
						"req": false,
						"type": "`$STRING`",
						"index$": 8,
					},
					map[string]any{
						"active": true,
						"name": "link",
						"req": false,
						"type": "`$STRING`",
						"index$": 9,
					},
					map[string]any{
						"active": true,
						"name": "name",
						"req": false,
						"type": "`$STRING`",
						"index$": 10,
					},
					map[string]any{
						"active": true,
						"name": "notice_type",
						"req": false,
						"type": "`$STRING`",
						"index$": 11,
					},
					map[string]any{
						"active": true,
						"name": "official_language",
						"req": false,
						"type": "`$STRING`",
						"index$": 12,
					},
					map[string]any{
						"active": true,
						"name": "pdf",
						"req": false,
						"type": "`$STRING`",
						"index$": 13,
					},
					map[string]any{
						"active": true,
						"name": "place_of_performance",
						"req": false,
						"type": "`$STRING`",
						"index$": 14,
					},
					map[string]any{
						"active": true,
						"name": "postcode",
						"req": false,
						"type": "`$STRING`",
						"index$": 15,
					},
					map[string]any{
						"active": true,
						"name": "procedure_type",
						"req": false,
						"type": "`$STRING`",
						"index$": 16,
					},
					map[string]any{
						"active": true,
						"name": "publication_date",
						"req": false,
						"type": "`$STRING`",
						"index$": 17,
					},
					map[string]any{
						"active": true,
						"name": "response_date",
						"req": false,
						"type": "`$STRING`",
						"index$": 18,
					},
					map[string]any{
						"active": true,
						"name": "title",
						"req": false,
						"type": "`$STRING`",
						"index$": 19,
					},
					map[string]any{
						"active": true,
						"name": "vat",
						"req": false,
						"type": "`$STRING`",
						"index$": 20,
					},
				},
				"name": "eu_ap_i",
				"op": map[string]any{
					"list": map[string]any{
						"input": "data",
						"name": "list",
						"points": []any{
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"example": "37080091",
											"kind": "query",
											"name": "q",
											"orig": "q",
											"reqd": true,
											"type": "`$STRING`",
										},
									},
								},
								"kind": "http",
								"method": "GET",
								"orig": "/tender",
								"parts": []any{
									"tender",
								},
								"select": map[string]any{
									"exist": []any{
										"q",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.tender`",
								},
								"index$": 0,
							},
						},
					},
					"load": map[string]any{
						"input": "data",
						"name": "load",
						"points": []any{
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"example": "NL001672022B01",
											"kind": "query",
											"name": "vat",
											"orig": "vat",
											"reqd": true,
											"type": "`$STRING`",
										},
									},
								},
								"kind": "http",
								"method": "GET",
								"orig": "/vat",
								"parts": []any{
									"vat",
								},
								"select": map[string]any{
									"exist": []any{
										"vat",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.vat`",
								},
								"index$": 0,
							},
						},
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
			"global_ap_i": map[string]any{
				"fields": []any{
					map[string]any{
						"active": true,
						"name": "addition",
						"req": false,
						"type": "`$STRING`",
						"index$": 0,
					},
					map[string]any{
						"active": true,
						"name": "address",
						"req": false,
						"type": "`$STRING`",
						"index$": 1,
					},
					map[string]any{
						"active": true,
						"name": "admin1",
						"req": false,
						"type": "`$STRING`",
						"index$": 2,
					},
					map[string]any{
						"active": true,
						"name": "admin2",
						"req": false,
						"type": "`$STRING`",
						"index$": 3,
					},
					map[string]any{
						"active": true,
						"name": "admin3",
						"req": false,
						"type": "`$STRING`",
						"index$": 4,
					},
					map[string]any{
						"active": true,
						"name": "bank",
						"req": false,
						"type": "`$STRING`",
						"index$": 5,
					},
					map[string]any{
						"active": true,
						"name": "bic",
						"req": false,
						"type": "`$STRING`",
						"index$": 6,
					},
					map[string]any{
						"active": true,
						"name": "browser",
						"req": false,
						"type": "`$STRING`",
						"index$": 7,
					},
					map[string]any{
						"active": true,
						"name": "builtwith",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 8,
					},
					map[string]any{
						"active": true,
						"name": "carrier",
						"req": false,
						"type": "`$STRING`",
						"index$": 9,
					},
					map[string]any{
						"active": true,
						"name": "city",
						"req": false,
						"type": "`$STRING`",
						"index$": 10,
					},
					map[string]any{
						"active": true,
						"name": "cloudflare",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 11,
					},
					map[string]any{
						"active": true,
						"name": "commoncrawl",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 12,
					},
					map[string]any{
						"active": true,
						"name": "content_length",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 13,
					},
					map[string]any{
						"active": true,
						"name": "content_type",
						"req": false,
						"type": "`$STRING`",
						"index$": 14,
					},
					map[string]any{
						"active": true,
						"name": "country",
						"req": false,
						"type": "`$STRING`",
						"index$": 15,
					},
					map[string]any{
						"active": true,
						"name": "country_code",
						"req": false,
						"type": "`$STRING`",
						"index$": 16,
					},
					map[string]any{
						"active": true,
						"name": "crux",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 17,
					},
					map[string]any{
						"active": true,
						"name": "device_family",
						"req": false,
						"type": "`$STRING`",
						"index$": 18,
					},
					map[string]any{
						"active": true,
						"name": "device_name",
						"req": false,
						"type": "`$STRING`",
						"index$": 19,
					},
					map[string]any{
						"active": true,
						"name": "device_type",
						"req": false,
						"type": "`$STRING`",
						"index$": 20,
					},
					map[string]any{
						"active": true,
						"name": "disposable",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 21,
					},
					map[string]any{
						"active": true,
						"name": "dns_a",
						"req": false,
						"type": "`$ARRAY`",
						"index$": 22,
					},
					map[string]any{
						"active": true,
						"name": "dns_mx",
						"req": false,
						"type": "`$ARRAY`",
						"index$": 23,
					},
					map[string]any{
						"active": true,
						"name": "dns_ns",
						"req": false,
						"type": "`$ARRAY`",
						"index$": 24,
					},
					map[string]any{
						"active": true,
						"name": "dns_soa",
						"req": false,
						"type": "`$ARRAY`",
						"index$": 25,
					},
					map[string]any{
						"active": true,
						"name": "dns_txt",
						"req": false,
						"type": "`$ARRAY`",
						"index$": 26,
					},
					map[string]any{
						"active": true,
						"name": "dns_www_a",
						"req": false,
						"type": "`$ARRAY`",
						"index$": 27,
					},
					map[string]any{
						"active": true,
						"name": "dnsserver",
						"req": false,
						"type": "`$STRING`",
						"index$": 28,
					},
					map[string]any{
						"active": true,
						"name": "domain",
						"req": false,
						"type": "`$STRING`",
						"index$": 29,
					},
					map[string]any{
						"active": true,
						"name": "domcop",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 30,
					},
					map[string]any{
						"active": true,
						"name": "email",
						"req": false,
						"type": "`$STRING`",
						"index$": 31,
					},
					map[string]any{
						"active": true,
						"name": "found",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 32,
					},
					map[string]any{
						"active": true,
						"name": "free",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 33,
					},
					map[string]any{
						"active": true,
						"name": "freeformaddress",
						"req": false,
						"type": "`$STRING`",
						"index$": 34,
					},
					map[string]any{
						"active": true,
						"name": "host",
						"req": false,
						"type": "`$STRING`",
						"index$": 35,
					},
					map[string]any{
						"active": true,
						"name": "host_type",
						"req": false,
						"type": "`$STRING`",
						"index$": 36,
					},
					map[string]any{
						"active": true,
						"name": "hostio",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 37,
					},
					map[string]any{
						"active": true,
						"name": "http_code",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 38,
					},
					map[string]any{
						"active": true,
						"name": "iban",
						"req": false,
						"type": "`$STRING`",
						"index$": 39,
					},
					map[string]any{
						"active": true,
						"name": "iban_human",
						"req": false,
						"type": "`$STRING`",
						"index$": 40,
					},
					map[string]any{
						"active": true,
						"name": "int",
						"req": false,
						"type": "`$STRING`",
						"index$": 41,
					},
					map[string]any{
						"active": true,
						"name": "international",
						"req": false,
						"type": "`$STRING`",
						"index$": 42,
					},
					map[string]any{
						"active": true,
						"name": "ip",
						"req": false,
						"type": "`$STRING`",
						"index$": 43,
					},
					map[string]any{
						"active": true,
						"name": "ipint",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 44,
					},
					map[string]any{
						"active": true,
						"name": "ismobile",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 45,
					},
					map[string]any{
						"active": true,
						"name": "lat",
						"req": false,
						"type": "`$NUMBER`",
						"index$": 46,
					},
					map[string]any{
						"active": true,
						"name": "lei",
						"req": false,
						"type": "`$STRING`",
						"index$": 47,
					},
					map[string]any{
						"active": true,
						"name": "letter",
						"req": false,
						"type": "`$STRING`",
						"index$": 48,
					},
					map[string]any{
						"active": true,
						"name": "local_id",
						"req": false,
						"type": "`$STRING`",
						"index$": 49,
					},
					map[string]any{
						"active": true,
						"name": "lon",
						"req": false,
						"type": "`$NUMBER`",
						"index$": 50,
					},
					map[string]any{
						"active": true,
						"name": "mailserver",
						"req": false,
						"type": "`$STRING`",
						"index$": 51,
					},
					map[string]any{
						"active": true,
						"name": "majestic",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 52,
					},
					map[string]any{
						"active": true,
						"name": "message",
						"req": false,
						"type": "`$STRING`",
						"index$": 53,
					},
					map[string]any{
						"active": true,
						"name": "municipality",
						"req": false,
						"type": "`$STRING`",
						"index$": 54,
					},
					map[string]any{
						"active": true,
						"name": "mx_host",
						"req": false,
						"type": "`$STRING`",
						"index$": 55,
					},
					map[string]any{
						"active": true,
						"name": "mx_ip",
						"req": false,
						"type": "`$STRING`",
						"index$": 56,
					},
					map[string]any{
						"active": true,
						"name": "name",
						"req": false,
						"type": "`$STRING`",
						"index$": 57,
					},
					map[string]any{
						"active": true,
						"name": "national",
						"req": false,
						"type": "`$STRING`",
						"index$": 58,
					},
					map[string]any{
						"active": true,
						"name": "number",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 59,
					},
					map[string]any{
						"active": true,
						"name": "ocid",
						"req": false,
						"type": "`$STRING`",
						"index$": 60,
					},
					map[string]any{
						"active": true,
						"name": "pagerank",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 61,
					},
					map[string]any{
						"active": true,
						"name": "platform",
						"req": false,
						"type": "`$STRING`",
						"index$": 62,
					},
					map[string]any{
						"active": true,
						"name": "population",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 63,
					},
					map[string]any{
						"active": true,
						"name": "postcode",
						"req": false,
						"type": "`$STRING`",
						"index$": 64,
					},
					map[string]any{
						"active": true,
						"name": "province",
						"req": false,
						"type": "`$STRING`",
						"index$": 65,
					},
					map[string]any{
						"active": true,
						"name": "province_code",
						"req": false,
						"type": "`$STRING`",
						"index$": 66,
					},
					map[string]any{
						"active": true,
						"name": "redirect_count",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 67,
					},
					map[string]any{
						"active": true,
						"name": "region",
						"req": false,
						"type": "`$STRING`",
						"index$": 68,
					},
					map[string]any{
						"active": true,
						"name": "register_id",
						"req": false,
						"type": "`$STRING`",
						"index$": 69,
					},
					map[string]any{
						"active": true,
						"name": "renewal_date",
						"req": false,
						"type": "`$STRING`",
						"index$": 70,
					},
					map[string]any{
						"active": true,
						"name": "score",
						"req": false,
						"type": "`$NUMBER`",
						"index$": 71,
					},
					map[string]any{
						"active": true,
						"name": "sepa",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 72,
					},
					map[string]any{
						"active": true,
						"name": "spf",
						"req": false,
						"type": "`$STRING`",
						"index$": 73,
					},
					map[string]any{
						"active": true,
						"name": "status",
						"req": false,
						"type": "`$STRING`",
						"index$": 74,
					},
					map[string]any{
						"active": true,
						"name": "street",
						"req": false,
						"type": "`$STRING`",
						"index$": 75,
					},
					map[string]any{
						"active": true,
						"name": "success",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 76,
					},
					map[string]any{
						"active": true,
						"name": "swift",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 77,
					},
					map[string]any{
						"active": true,
						"name": "tranco",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 78,
					},
					map[string]any{
						"active": true,
						"name": "type",
						"req": false,
						"type": "`$STRING`",
						"index$": 79,
					},
					map[string]any{
						"active": true,
						"name": "umbrella",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 80,
					},
					map[string]any{
						"active": true,
						"name": "url",
						"req": false,
						"type": "`$STRING`",
						"index$": 81,
					},
					map[string]any{
						"active": true,
						"name": "user",
						"req": false,
						"type": "`$STRING`",
						"index$": 82,
					},
					map[string]any{
						"active": true,
						"name": "user_agent",
						"req": false,
						"type": "`$STRING`",
						"index$": 83,
					},
					map[string]any{
						"active": true,
						"name": "valid",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 84,
					},
					map[string]any{
						"active": true,
						"name": "verified",
						"req": false,
						"type": "`$BOOLEAN`",
						"index$": 85,
					},
					map[string]any{
						"active": true,
						"name": "verified_checksum",
						"req": false,
						"type": "`$BOOLEAN`",
						"index$": 86,
					},
					map[string]any{
						"active": true,
						"name": "webrank",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 87,
					},
					map[string]any{
						"active": true,
						"name": "wrong_email",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 88,
					},
					map[string]any{
						"active": true,
						"name": "wrong_format",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 89,
					},
					map[string]any{
						"active": true,
						"name": "wrong_password",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 90,
					},
					map[string]any{
						"active": true,
						"name": "wrong_phone",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 91,
					},
				},
				"name": "global_ap_i",
				"op": map[string]any{
					"create": map[string]any{
						"input": "data",
						"name": "create",
						"points": []any{
							map[string]any{
								"active": true,
								"args": map[string]any{},
								"kind": "http",
								"method": "POST",
								"orig": "/password",
								"parts": []any{
									"password",
								},
								"select": map[string]any{},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.password`",
								},
								"index$": 0,
							},
						},
					},
					"list": map[string]any{
						"input": "data",
						"name": "list",
						"points": []any{
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"example": "Haarlem",
											"kind": "query",
											"name": "city",
											"orig": "city",
											"reqd": true,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": "NL",
											"kind": "query",
											"name": "country_code",
											"orig": "country_code",
											"reqd": true,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "full",
											"orig": "full",
											"reqd": false,
											"type": "`$INTEGER`",
										},
									},
								},
								"kind": "http",
								"method": "GET",
								"orig": "/city",
								"parts": []any{
									"city",
								},
								"select": map[string]any{
									"exist": []any{
										"city",
										"country_code",
										"full",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.city`",
								},
								"index$": 0,
							},
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"example": "NL",
											"kind": "query",
											"name": "country_code",
											"orig": "country_code",
											"reqd": true,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": "1013PN",
											"kind": "query",
											"name": "postcode",
											"orig": "postcode",
											"reqd": true,
											"type": "`$STRING`",
										},
									},
								},
								"kind": "http",
								"method": "GET",
								"orig": "/postcode",
								"parts": []any{
									"postcode",
								},
								"select": map[string]any{
									"exist": []any{
										"country_code",
										"postcode",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.postcode`",
								},
								"index$": 1,
							},
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"example": "nl",
											"kind": "query",
											"name": "country_code",
											"orig": "country_code",
											"reqd": true,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": "Kalverstraat 1, 1012NX",
											"kind": "query",
											"name": "q",
											"orig": "q",
											"reqd": true,
											"type": "`$STRING`",
										},
									},
								},
								"kind": "http",
								"method": "GET",
								"orig": "/geocoding",
								"parts": []any{
									"geocoding",
								},
								"select": map[string]any{
									"exist": []any{
										"country_code",
										"q",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.geocoding`",
								},
								"index$": 2,
							},
						},
					},
					"load": map[string]any{
						"input": "data",
						"name": "load",
						"points": []any{
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"example": "AKZONL2AXXX",
											"kind": "query",
											"name": "bic",
											"orig": "bic",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": "724500XYIJUGXAA5QD70",
											"kind": "query",
											"name": "lei",
											"orig": "lei",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": "09007809",
											"kind": "query",
											"name": "local_id",
											"orig": "local_id",
											"reqd": false,
											"type": "`$STRING`",
										},
									},
								},
								"kind": "http",
								"method": "GET",
								"orig": "/lei",
								"parts": []any{
									"lei",
								},
								"select": map[string]any{
									"exist": []any{
										"bic",
										"lei",
										"local_id",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.lei`",
								},
								"index$": 0,
							},
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "password",
											"orig": "password",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": "2c4c3891e2ac6958e9810a1e49c6705784fbfa1a",
											"kind": "query",
											"name": "password_sha1",
											"orig": "password_sha1",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": 25,
											"kind": "query",
											"name": "threshold",
											"orig": "threshold",
											"reqd": false,
											"type": "`$INTEGER`",
										},
									},
								},
								"kind": "http",
								"method": "GET",
								"orig": "/password",
								"parts": []any{
									"password",
								},
								"select": map[string]any{
									"exist": []any{
										"password",
										"password_sha1",
										"threshold",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.password`",
								},
								"index$": 1,
							},
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"example": "nl",
											"kind": "query",
											"name": "country_code",
											"orig": "country_code",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": "+31207895050",
											"kind": "query",
											"name": "phone",
											"orig": "phone",
											"reqd": true,
											"type": "`$STRING`",
										},
									},
								},
								"kind": "http",
								"method": "GET",
								"orig": "/phone",
								"parts": []any{
									"phone",
								},
								"select": map[string]any{
									"exist": []any{
										"country_code",
										"phone",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.phone`",
								},
								"index$": 2,
							},
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"example": "AKZONL2A",
											"kind": "query",
											"name": "bic",
											"orig": "bic",
											"reqd": true,
											"type": "`$STRING`",
										},
									},
								},
								"kind": "http",
								"method": "GET",
								"orig": "/bic",
								"parts": []any{
									"bic",
								},
								"select": map[string]any{
									"exist": []any{
										"bic",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.bic`",
								},
								"index$": 3,
							},
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"example": "eur",
											"kind": "query",
											"name": "currency",
											"orig": "currency",
											"reqd": true,
											"type": "`$STRING`",
										},
									},
								},
								"kind": "http",
								"method": "GET",
								"orig": "/currency",
								"parts": []any{
									"currency",
								},
								"select": map[string]any{
									"exist": []any{
										"currency",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.currency`",
								},
								"index$": 4,
							},
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"example": "bedrijfsdata.nl",
											"kind": "query",
											"name": "domain",
											"orig": "domain",
											"reqd": true,
											"type": "`$STRING`",
										},
									},
								},
								"kind": "http",
								"method": "GET",
								"orig": "/dns",
								"parts": []any{
									"dns",
								},
								"select": map[string]any{
									"exist": []any{
										"domain",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.dns`",
								},
								"index$": 5,
							},
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"example": "google.com",
											"kind": "query",
											"name": "domain",
											"orig": "domain",
											"reqd": true,
											"type": "`$STRING`",
										},
									},
								},
								"kind": "http",
								"method": "GET",
								"orig": "/webrank",
								"parts": []any{
									"webrank",
								},
								"select": map[string]any{
									"exist": []any{
										"domain",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.webrank`",
								},
								"index$": 6,
							},
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"example": "piet@bedrijfsdata.nl",
											"kind": "query",
											"name": "email",
											"orig": "email",
											"reqd": true,
											"type": "`$STRING`",
										},
									},
								},
								"kind": "http",
								"method": "GET",
								"orig": "/email",
								"parts": []any{
									"email",
								},
								"select": map[string]any{
									"exist": []any{
										"email",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.email`",
								},
								"index$": 7,
							},
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"example": "NL17ADYB2017400505",
											"kind": "query",
											"name": "iban",
											"orig": "iban",
											"reqd": true,
											"type": "`$STRING`",
										},
									},
								},
								"kind": "http",
								"method": "GET",
								"orig": "/iban",
								"parts": []any{
									"iban",
								},
								"select": map[string]any{
									"exist": []any{
										"iban",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.iban`",
								},
								"index$": 8,
							},
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "ua",
											"orig": "ua",
											"reqd": false,
											"type": "`$INTEGER`",
										},
									},
								},
								"kind": "http",
								"method": "GET",
								"orig": "/ip",
								"parts": []any{
									"ip",
								},
								"select": map[string]any{
									"exist": []any{
										"ua",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.ip`",
								},
								"index$": 9,
							},
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"example": "http://www.bedrijfsdata.nl",
											"kind": "query",
											"name": "url",
											"orig": "url",
											"reqd": true,
											"type": "`$STRING`",
										},
									},
								},
								"kind": "http",
								"method": "GET",
								"orig": "/url",
								"parts": []any{
									"url",
								},
								"select": map[string]any{
									"exist": []any{
										"url",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.url`",
								},
								"index$": 10,
							},
						},
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
			"netherlands_ap_i": map[string]any{
				"fields": []any{
					map[string]any{
						"active": true,
						"name": "active",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 0,
					},
					map[string]any{
						"active": true,
						"name": "addition",
						"req": false,
						"type": "`$STRING`",
						"index$": 1,
					},
					map[string]any{
						"active": true,
						"name": "city",
						"req": false,
						"type": "`$STRING`",
						"index$": 2,
					},
					map[string]any{
						"active": true,
						"name": "coc",
						"req": false,
						"type": "`$STRING`",
						"index$": 3,
					},
					map[string]any{
						"active": true,
						"name": "construction_year",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 4,
					},
					map[string]any{
						"active": true,
						"name": "floor_area",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 5,
					},
					map[string]any{
						"active": true,
						"name": "freeformaddress",
						"req": false,
						"type": "`$STRING`",
						"index$": 6,
					},
					map[string]any{
						"active": true,
						"name": "id",
						"req": false,
						"type": "`$STRING`",
						"index$": 7,
					},
					map[string]any{
						"active": true,
						"name": "lat",
						"req": false,
						"type": "`$NUMBER`",
						"index$": 8,
					},
					map[string]any{
						"active": true,
						"name": "letter",
						"req": false,
						"type": "`$STRING`",
						"index$": 9,
					},
					map[string]any{
						"active": true,
						"name": "lon",
						"req": false,
						"type": "`$NUMBER`",
						"index$": 10,
					},
					map[string]any{
						"active": true,
						"name": "municipality",
						"req": false,
						"type": "`$STRING`",
						"index$": 11,
					},
					map[string]any{
						"active": true,
						"name": "name",
						"req": false,
						"type": "`$STRING`",
						"index$": 12,
					},
					map[string]any{
						"active": true,
						"name": "number",
						"req": false,
						"type": "`$STRING`",
						"index$": 13,
					},
					map[string]any{
						"active": true,
						"name": "postcode",
						"req": false,
						"type": "`$STRING`",
						"index$": 14,
					},
					map[string]any{
						"active": true,
						"name": "province",
						"req": false,
						"type": "`$STRING`",
						"index$": 15,
					},
					map[string]any{
						"active": true,
						"name": "province_code",
						"req": false,
						"type": "`$STRING`",
						"index$": 16,
					},
					map[string]any{
						"active": true,
						"name": "purpose",
						"req": false,
						"type": "`$STRING`",
						"index$": 17,
					},
					map[string]any{
						"active": true,
						"name": "street",
						"req": false,
						"type": "`$STRING`",
						"index$": 18,
					},
					map[string]any{
						"active": true,
						"name": "type",
						"req": false,
						"type": "`$STRING`",
						"index$": 19,
					},
					map[string]any{
						"active": true,
						"name": "vestiging",
						"req": false,
						"type": "`$STRING`",
						"index$": 20,
					},
				},
				"name": "netherlands_ap_i",
				"op": map[string]any{
					"list": map[string]any{
						"input": "data",
						"name": "list",
						"points": []any{
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"example": "3",
											"kind": "query",
											"name": "number",
											"orig": "number",
											"reqd": true,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": "1011PN",
											"kind": "query",
											"name": "postcode",
											"orig": "postcode",
											"reqd": true,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": "a",
											"kind": "query",
											"name": "suffix",
											"orig": "suffix",
											"reqd": false,
											"type": "`$STRING`",
										},
									},
								},
								"kind": "http",
								"method": "GET",
								"orig": "/bag",
								"parts": []any{
									"bag",
								},
								"select": map[string]any{
									"exist": []any{
										"number",
										"postcode",
										"suffix",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.bag`",
								},
								"index$": 0,
							},
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"example": "89395808",
											"kind": "query",
											"name": "kvk",
											"orig": "kvk",
											"reqd": true,
											"type": "`$STRING`",
										},
									},
								},
								"kind": "http",
								"method": "GET",
								"orig": "/kvk",
								"parts": []any{
									"kvk",
								},
								"select": map[string]any{
									"exist": []any{
										"kvk",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body.kvk`",
								},
								"index$": 1,
							},
						},
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
		},
	}
}

func makeFeature(name string) Feature {
	switch name {
	case "test":
		if NewTestFeatureFunc != nil {
			return NewTestFeatureFunc()
		}
	default:
		if NewBaseFeatureFunc != nil {
			return NewBaseFeatureFunc()
		}
	}
	return nil
}
