# DutchCustomerData SDK configuration


def make_config():
    return {
        "main": {
            "name": "DutchCustomerData",
        },
        "feature": {
            "test": {
        "options": {
          "active": False,
        },
      },
        },
        "options": {
            "base": "https://free.bedrijfsdata.nl/v1.1",
            "headers": {
        "content-type": "application/json",
      },
            "entity": {
                "eu_ap_i": {},
                "global_ap_i": {},
                "netherlands_ap_i": {},
            },
        },
        "entity": {
      "eu_ap_i": {
        "fields": [
          {
            "active": True,
            "name": "active",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 0,
          },
          {
            "active": True,
            "name": "address",
            "req": False,
            "type": "`$STRING`",
            "index$": 1,
          },
          {
            "active": True,
            "name": "buyer",
            "req": False,
            "type": "`$STRING`",
            "index$": 2,
          },
          {
            "active": True,
            "name": "buyer_country",
            "req": False,
            "type": "`$STRING`",
            "index$": 3,
          },
          {
            "active": True,
            "name": "city",
            "req": False,
            "type": "`$STRING`",
            "index$": 4,
          },
          {
            "active": True,
            "name": "contract_nature",
            "req": False,
            "type": "`$STRING`",
            "index$": 5,
          },
          {
            "active": True,
            "name": "country",
            "req": False,
            "type": "`$STRING`",
            "index$": 6,
          },
          {
            "active": True,
            "name": "html",
            "req": False,
            "type": "`$STRING`",
            "index$": 7,
          },
          {
            "active": True,
            "name": "id",
            "req": False,
            "type": "`$STRING`",
            "index$": 8,
          },
          {
            "active": True,
            "name": "link",
            "req": False,
            "type": "`$STRING`",
            "index$": 9,
          },
          {
            "active": True,
            "name": "name",
            "req": False,
            "type": "`$STRING`",
            "index$": 10,
          },
          {
            "active": True,
            "name": "notice_type",
            "req": False,
            "type": "`$STRING`",
            "index$": 11,
          },
          {
            "active": True,
            "name": "official_language",
            "req": False,
            "type": "`$STRING`",
            "index$": 12,
          },
          {
            "active": True,
            "name": "pdf",
            "req": False,
            "type": "`$STRING`",
            "index$": 13,
          },
          {
            "active": True,
            "name": "place_of_performance",
            "req": False,
            "type": "`$STRING`",
            "index$": 14,
          },
          {
            "active": True,
            "name": "postcode",
            "req": False,
            "type": "`$STRING`",
            "index$": 15,
          },
          {
            "active": True,
            "name": "procedure_type",
            "req": False,
            "type": "`$STRING`",
            "index$": 16,
          },
          {
            "active": True,
            "name": "publication_date",
            "req": False,
            "type": "`$STRING`",
            "index$": 17,
          },
          {
            "active": True,
            "name": "response_date",
            "req": False,
            "type": "`$STRING`",
            "index$": 18,
          },
          {
            "active": True,
            "name": "title",
            "req": False,
            "type": "`$STRING`",
            "index$": 19,
          },
          {
            "active": True,
            "name": "vat",
            "req": False,
            "type": "`$STRING`",
            "index$": 20,
          },
        ],
        "name": "eu_ap_i",
        "op": {
          "list": {
            "input": "data",
            "name": "list",
            "points": [
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": "37080091",
                      "kind": "query",
                      "name": "q",
                      "orig": "q",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/tender",
                "parts": [
                  "tender",
                ],
                "select": {
                  "exist": [
                    "q",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.tender`",
                },
                "index$": 0,
              },
            ],
            "key$": "list",
          },
          "load": {
            "input": "data",
            "name": "load",
            "points": [
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": "NL001672022B01",
                      "kind": "query",
                      "name": "vat",
                      "orig": "vat",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/vat",
                "parts": [
                  "vat",
                ],
                "select": {
                  "exist": [
                    "vat",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.vat`",
                },
                "index$": 0,
              },
            ],
            "key$": "load",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
      "global_ap_i": {
        "fields": [
          {
            "active": True,
            "name": "addition",
            "req": False,
            "type": "`$STRING`",
            "index$": 0,
          },
          {
            "active": True,
            "name": "address",
            "req": False,
            "type": "`$STRING`",
            "index$": 1,
          },
          {
            "active": True,
            "name": "admin1",
            "req": False,
            "type": "`$STRING`",
            "index$": 2,
          },
          {
            "active": True,
            "name": "admin2",
            "req": False,
            "type": "`$STRING`",
            "index$": 3,
          },
          {
            "active": True,
            "name": "admin3",
            "req": False,
            "type": "`$STRING`",
            "index$": 4,
          },
          {
            "active": True,
            "name": "bank",
            "req": False,
            "type": "`$STRING`",
            "index$": 5,
          },
          {
            "active": True,
            "name": "bic",
            "req": False,
            "type": "`$STRING`",
            "index$": 6,
          },
          {
            "active": True,
            "name": "browser",
            "req": False,
            "type": "`$STRING`",
            "index$": 7,
          },
          {
            "active": True,
            "name": "builtwith",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 8,
          },
          {
            "active": True,
            "name": "carrier",
            "req": False,
            "type": "`$STRING`",
            "index$": 9,
          },
          {
            "active": True,
            "name": "city",
            "req": False,
            "type": "`$STRING`",
            "index$": 10,
          },
          {
            "active": True,
            "name": "cloudflare",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 11,
          },
          {
            "active": True,
            "name": "commoncrawl",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 12,
          },
          {
            "active": True,
            "name": "content_length",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 13,
          },
          {
            "active": True,
            "name": "content_type",
            "req": False,
            "type": "`$STRING`",
            "index$": 14,
          },
          {
            "active": True,
            "name": "country",
            "req": False,
            "type": "`$STRING`",
            "index$": 15,
          },
          {
            "active": True,
            "name": "country_code",
            "req": False,
            "type": "`$STRING`",
            "index$": 16,
          },
          {
            "active": True,
            "name": "crux",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 17,
          },
          {
            "active": True,
            "name": "device_family",
            "req": False,
            "type": "`$STRING`",
            "index$": 18,
          },
          {
            "active": True,
            "name": "device_name",
            "req": False,
            "type": "`$STRING`",
            "index$": 19,
          },
          {
            "active": True,
            "name": "device_type",
            "req": False,
            "type": "`$STRING`",
            "index$": 20,
          },
          {
            "active": True,
            "name": "disposable",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 21,
          },
          {
            "active": True,
            "name": "dns_a",
            "req": False,
            "type": "`$ARRAY`",
            "index$": 22,
          },
          {
            "active": True,
            "name": "dns_mx",
            "req": False,
            "type": "`$ARRAY`",
            "index$": 23,
          },
          {
            "active": True,
            "name": "dns_ns",
            "req": False,
            "type": "`$ARRAY`",
            "index$": 24,
          },
          {
            "active": True,
            "name": "dns_soa",
            "req": False,
            "type": "`$ARRAY`",
            "index$": 25,
          },
          {
            "active": True,
            "name": "dns_txt",
            "req": False,
            "type": "`$ARRAY`",
            "index$": 26,
          },
          {
            "active": True,
            "name": "dns_www_a",
            "req": False,
            "type": "`$ARRAY`",
            "index$": 27,
          },
          {
            "active": True,
            "name": "dnsserver",
            "req": False,
            "type": "`$STRING`",
            "index$": 28,
          },
          {
            "active": True,
            "name": "domain",
            "req": False,
            "type": "`$STRING`",
            "index$": 29,
          },
          {
            "active": True,
            "name": "domcop",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 30,
          },
          {
            "active": True,
            "name": "email",
            "req": False,
            "type": "`$STRING`",
            "index$": 31,
          },
          {
            "active": True,
            "name": "found",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 32,
          },
          {
            "active": True,
            "name": "free",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 33,
          },
          {
            "active": True,
            "name": "freeformaddress",
            "req": False,
            "type": "`$STRING`",
            "index$": 34,
          },
          {
            "active": True,
            "name": "host",
            "req": False,
            "type": "`$STRING`",
            "index$": 35,
          },
          {
            "active": True,
            "name": "host_type",
            "req": False,
            "type": "`$STRING`",
            "index$": 36,
          },
          {
            "active": True,
            "name": "hostio",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 37,
          },
          {
            "active": True,
            "name": "http_code",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 38,
          },
          {
            "active": True,
            "name": "iban",
            "req": False,
            "type": "`$STRING`",
            "index$": 39,
          },
          {
            "active": True,
            "name": "iban_human",
            "req": False,
            "type": "`$STRING`",
            "index$": 40,
          },
          {
            "active": True,
            "name": "int",
            "req": False,
            "type": "`$STRING`",
            "index$": 41,
          },
          {
            "active": True,
            "name": "international",
            "req": False,
            "type": "`$STRING`",
            "index$": 42,
          },
          {
            "active": True,
            "name": "ip",
            "req": False,
            "type": "`$STRING`",
            "index$": 43,
          },
          {
            "active": True,
            "name": "ipint",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 44,
          },
          {
            "active": True,
            "name": "ismobile",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 45,
          },
          {
            "active": True,
            "name": "lat",
            "req": False,
            "type": "`$NUMBER`",
            "index$": 46,
          },
          {
            "active": True,
            "name": "lei",
            "req": False,
            "type": "`$STRING`",
            "index$": 47,
          },
          {
            "active": True,
            "name": "letter",
            "req": False,
            "type": "`$STRING`",
            "index$": 48,
          },
          {
            "active": True,
            "name": "local_id",
            "req": False,
            "type": "`$STRING`",
            "index$": 49,
          },
          {
            "active": True,
            "name": "lon",
            "req": False,
            "type": "`$NUMBER`",
            "index$": 50,
          },
          {
            "active": True,
            "name": "mailserver",
            "req": False,
            "type": "`$STRING`",
            "index$": 51,
          },
          {
            "active": True,
            "name": "majestic",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 52,
          },
          {
            "active": True,
            "name": "message",
            "req": False,
            "type": "`$STRING`",
            "index$": 53,
          },
          {
            "active": True,
            "name": "municipality",
            "req": False,
            "type": "`$STRING`",
            "index$": 54,
          },
          {
            "active": True,
            "name": "mx_host",
            "req": False,
            "type": "`$STRING`",
            "index$": 55,
          },
          {
            "active": True,
            "name": "mx_ip",
            "req": False,
            "type": "`$STRING`",
            "index$": 56,
          },
          {
            "active": True,
            "name": "name",
            "req": False,
            "type": "`$STRING`",
            "index$": 57,
          },
          {
            "active": True,
            "name": "national",
            "req": False,
            "type": "`$STRING`",
            "index$": 58,
          },
          {
            "active": True,
            "name": "number",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 59,
          },
          {
            "active": True,
            "name": "ocid",
            "req": False,
            "type": "`$STRING`",
            "index$": 60,
          },
          {
            "active": True,
            "name": "pagerank",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 61,
          },
          {
            "active": True,
            "name": "platform",
            "req": False,
            "type": "`$STRING`",
            "index$": 62,
          },
          {
            "active": True,
            "name": "population",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 63,
          },
          {
            "active": True,
            "name": "postcode",
            "req": False,
            "type": "`$STRING`",
            "index$": 64,
          },
          {
            "active": True,
            "name": "province",
            "req": False,
            "type": "`$STRING`",
            "index$": 65,
          },
          {
            "active": True,
            "name": "province_code",
            "req": False,
            "type": "`$STRING`",
            "index$": 66,
          },
          {
            "active": True,
            "name": "redirect_count",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 67,
          },
          {
            "active": True,
            "name": "region",
            "req": False,
            "type": "`$STRING`",
            "index$": 68,
          },
          {
            "active": True,
            "name": "register_id",
            "req": False,
            "type": "`$STRING`",
            "index$": 69,
          },
          {
            "active": True,
            "name": "renewal_date",
            "req": False,
            "type": "`$STRING`",
            "index$": 70,
          },
          {
            "active": True,
            "name": "score",
            "req": False,
            "type": "`$NUMBER`",
            "index$": 71,
          },
          {
            "active": True,
            "name": "sepa",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 72,
          },
          {
            "active": True,
            "name": "spf",
            "req": False,
            "type": "`$STRING`",
            "index$": 73,
          },
          {
            "active": True,
            "name": "status",
            "req": False,
            "type": "`$STRING`",
            "index$": 74,
          },
          {
            "active": True,
            "name": "street",
            "req": False,
            "type": "`$STRING`",
            "index$": 75,
          },
          {
            "active": True,
            "name": "success",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 76,
          },
          {
            "active": True,
            "name": "swift",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 77,
          },
          {
            "active": True,
            "name": "tranco",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 78,
          },
          {
            "active": True,
            "name": "type",
            "req": False,
            "type": "`$STRING`",
            "index$": 79,
          },
          {
            "active": True,
            "name": "umbrella",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 80,
          },
          {
            "active": True,
            "name": "url",
            "req": False,
            "type": "`$STRING`",
            "index$": 81,
          },
          {
            "active": True,
            "name": "user",
            "req": False,
            "type": "`$STRING`",
            "index$": 82,
          },
          {
            "active": True,
            "name": "user_agent",
            "req": False,
            "type": "`$STRING`",
            "index$": 83,
          },
          {
            "active": True,
            "name": "valid",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 84,
          },
          {
            "active": True,
            "name": "verified",
            "req": False,
            "type": "`$BOOLEAN`",
            "index$": 85,
          },
          {
            "active": True,
            "name": "verified_checksum",
            "req": False,
            "type": "`$BOOLEAN`",
            "index$": 86,
          },
          {
            "active": True,
            "name": "webrank",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 87,
          },
          {
            "active": True,
            "name": "wrong_email",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 88,
          },
          {
            "active": True,
            "name": "wrong_format",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 89,
          },
          {
            "active": True,
            "name": "wrong_password",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 90,
          },
          {
            "active": True,
            "name": "wrong_phone",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 91,
          },
        ],
        "name": "global_ap_i",
        "op": {
          "create": {
            "input": "data",
            "name": "create",
            "points": [
              {
                "active": True,
                "args": {},
                "kind": "http",
                "method": "POST",
                "orig": "/password",
                "parts": [
                  "password",
                ],
                "select": {},
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.password`",
                },
                "index$": 0,
              },
            ],
            "key$": "create",
          },
          "list": {
            "input": "data",
            "name": "list",
            "points": [
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": "Haarlem",
                      "kind": "query",
                      "name": "city",
                      "orig": "city",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "NL",
                      "kind": "query",
                      "name": "country_code",
                      "orig": "country_code",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "full",
                      "orig": "full",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/city",
                "parts": [
                  "city",
                ],
                "select": {
                  "exist": [
                    "city",
                    "country_code",
                    "full",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.city`",
                },
                "index$": 0,
              },
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": "NL",
                      "kind": "query",
                      "name": "country_code",
                      "orig": "country_code",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "1013PN",
                      "kind": "query",
                      "name": "postcode",
                      "orig": "postcode",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/postcode",
                "parts": [
                  "postcode",
                ],
                "select": {
                  "exist": [
                    "country_code",
                    "postcode",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.postcode`",
                },
                "index$": 1,
              },
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": "nl",
                      "kind": "query",
                      "name": "country_code",
                      "orig": "country_code",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "Kalverstraat 1, 1012NX",
                      "kind": "query",
                      "name": "q",
                      "orig": "q",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/geocoding",
                "parts": [
                  "geocoding",
                ],
                "select": {
                  "exist": [
                    "country_code",
                    "q",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.geocoding`",
                },
                "index$": 2,
              },
            ],
            "key$": "list",
          },
          "load": {
            "input": "data",
            "name": "load",
            "points": [
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": "AKZONL2AXXX",
                      "kind": "query",
                      "name": "bic",
                      "orig": "bic",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "724500XYIJUGXAA5QD70",
                      "kind": "query",
                      "name": "lei",
                      "orig": "lei",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "09007809",
                      "kind": "query",
                      "name": "local_id",
                      "orig": "local_id",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/lei",
                "parts": [
                  "lei",
                ],
                "select": {
                  "exist": [
                    "bic",
                    "lei",
                    "local_id",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.lei`",
                },
                "index$": 0,
              },
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "kind": "query",
                      "name": "password",
                      "orig": "password",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "2c4c3891e2ac6958e9810a1e49c6705784fbfa1a",
                      "kind": "query",
                      "name": "password_sha1",
                      "orig": "password_sha1",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": 25,
                      "kind": "query",
                      "name": "threshold",
                      "orig": "threshold",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/password",
                "parts": [
                  "password",
                ],
                "select": {
                  "exist": [
                    "password",
                    "password_sha1",
                    "threshold",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.password`",
                },
                "index$": 1,
              },
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": "nl",
                      "kind": "query",
                      "name": "country_code",
                      "orig": "country_code",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "+31207895050",
                      "kind": "query",
                      "name": "phone",
                      "orig": "phone",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/phone",
                "parts": [
                  "phone",
                ],
                "select": {
                  "exist": [
                    "country_code",
                    "phone",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.phone`",
                },
                "index$": 2,
              },
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": "AKZONL2A",
                      "kind": "query",
                      "name": "bic",
                      "orig": "bic",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/bic",
                "parts": [
                  "bic",
                ],
                "select": {
                  "exist": [
                    "bic",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.bic`",
                },
                "index$": 3,
              },
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": "eur",
                      "kind": "query",
                      "name": "currency",
                      "orig": "currency",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/currency",
                "parts": [
                  "currency",
                ],
                "select": {
                  "exist": [
                    "currency",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.currency`",
                },
                "index$": 4,
              },
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": "bedrijfsdata.nl",
                      "kind": "query",
                      "name": "domain",
                      "orig": "domain",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/dns",
                "parts": [
                  "dns",
                ],
                "select": {
                  "exist": [
                    "domain",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.dns`",
                },
                "index$": 5,
              },
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": "google.com",
                      "kind": "query",
                      "name": "domain",
                      "orig": "domain",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/webrank",
                "parts": [
                  "webrank",
                ],
                "select": {
                  "exist": [
                    "domain",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.webrank`",
                },
                "index$": 6,
              },
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": "piet@bedrijfsdata.nl",
                      "kind": "query",
                      "name": "email",
                      "orig": "email",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/email",
                "parts": [
                  "email",
                ],
                "select": {
                  "exist": [
                    "email",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.email`",
                },
                "index$": 7,
              },
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": "NL17ADYB2017400505",
                      "kind": "query",
                      "name": "iban",
                      "orig": "iban",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/iban",
                "parts": [
                  "iban",
                ],
                "select": {
                  "exist": [
                    "iban",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.iban`",
                },
                "index$": 8,
              },
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "kind": "query",
                      "name": "ua",
                      "orig": "ua",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/ip",
                "parts": [
                  "ip",
                ],
                "select": {
                  "exist": [
                    "ua",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.ip`",
                },
                "index$": 9,
              },
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": "http://www.bedrijfsdata.nl",
                      "kind": "query",
                      "name": "url",
                      "orig": "url",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/url",
                "parts": [
                  "url",
                ],
                "select": {
                  "exist": [
                    "url",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.url`",
                },
                "index$": 10,
              },
            ],
            "key$": "load",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
      "netherlands_ap_i": {
        "fields": [
          {
            "active": True,
            "name": "active",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 0,
          },
          {
            "active": True,
            "name": "addition",
            "req": False,
            "type": "`$STRING`",
            "index$": 1,
          },
          {
            "active": True,
            "name": "city",
            "req": False,
            "type": "`$STRING`",
            "index$": 2,
          },
          {
            "active": True,
            "name": "coc",
            "req": False,
            "type": "`$STRING`",
            "index$": 3,
          },
          {
            "active": True,
            "name": "construction_year",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 4,
          },
          {
            "active": True,
            "name": "floor_area",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 5,
          },
          {
            "active": True,
            "name": "freeformaddress",
            "req": False,
            "type": "`$STRING`",
            "index$": 6,
          },
          {
            "active": True,
            "name": "id",
            "req": False,
            "type": "`$STRING`",
            "index$": 7,
          },
          {
            "active": True,
            "name": "lat",
            "req": False,
            "type": "`$NUMBER`",
            "index$": 8,
          },
          {
            "active": True,
            "name": "letter",
            "req": False,
            "type": "`$STRING`",
            "index$": 9,
          },
          {
            "active": True,
            "name": "lon",
            "req": False,
            "type": "`$NUMBER`",
            "index$": 10,
          },
          {
            "active": True,
            "name": "municipality",
            "req": False,
            "type": "`$STRING`",
            "index$": 11,
          },
          {
            "active": True,
            "name": "name",
            "req": False,
            "type": "`$STRING`",
            "index$": 12,
          },
          {
            "active": True,
            "name": "number",
            "req": False,
            "type": "`$STRING`",
            "index$": 13,
          },
          {
            "active": True,
            "name": "postcode",
            "req": False,
            "type": "`$STRING`",
            "index$": 14,
          },
          {
            "active": True,
            "name": "province",
            "req": False,
            "type": "`$STRING`",
            "index$": 15,
          },
          {
            "active": True,
            "name": "province_code",
            "req": False,
            "type": "`$STRING`",
            "index$": 16,
          },
          {
            "active": True,
            "name": "purpose",
            "req": False,
            "type": "`$STRING`",
            "index$": 17,
          },
          {
            "active": True,
            "name": "street",
            "req": False,
            "type": "`$STRING`",
            "index$": 18,
          },
          {
            "active": True,
            "name": "type",
            "req": False,
            "type": "`$STRING`",
            "index$": 19,
          },
          {
            "active": True,
            "name": "vestiging",
            "req": False,
            "type": "`$STRING`",
            "index$": 20,
          },
        ],
        "name": "netherlands_ap_i",
        "op": {
          "list": {
            "input": "data",
            "name": "list",
            "points": [
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": "3",
                      "kind": "query",
                      "name": "number",
                      "orig": "number",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "1011PN",
                      "kind": "query",
                      "name": "postcode",
                      "orig": "postcode",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "a",
                      "kind": "query",
                      "name": "suffix",
                      "orig": "suffix",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/bag",
                "parts": [
                  "bag",
                ],
                "select": {
                  "exist": [
                    "number",
                    "postcode",
                    "suffix",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.bag`",
                },
                "index$": 0,
              },
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": "89395808",
                      "kind": "query",
                      "name": "kvk",
                      "orig": "kvk",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/kvk",
                "parts": [
                  "kvk",
                ],
                "select": {
                  "exist": [
                    "kvk",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body.kvk`",
                },
                "index$": 1,
              },
            ],
            "key$": "list",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
    },
    }
